#ifndef WARSTWABIZNESOWA_GLOBAL_H
#define WARSTWABIZNESOWA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WARSTWABIZNESOWA_LIBRARY)
#define WARSTWABIZNESOWA_EXPORT Q_DECL_EXPORT
#else
#define WARSTWABIZNESOWA_EXPORT Q_DECL_IMPORT
#endif

#endif // WARSTWABIZNESOWA_GLOBAL_H
